# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 183cb671a650e035fefd4fb7c7a32fb6a53f4f9737fc39e522db710214f0c69b9532e9fa2ad476e69baf218b5d5e998e2280898dbe883c6e33d7040e7f9f8084

test:
  secret_key_base: 9c4f5b15faeeaba3c3310a3152adfe045663d2cd5f0e6b705312cc88d18b8ca72a9982beab28e00545c959dd82c82dda660b4988163fbb5a2f0cd492a66e28a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
